// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HotelReservation_EF.LoginEntity
{
    public partial class Frontend
    {
        public string UserName { get; set; }
        public string PassWord { get; set; }
    }
}