// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using HotelReservation_EF.ReservationEntity;

#nullable disable

namespace HotelReservation_EF
{
    public partial class ReservationContext : DbContext
    {
        public ReservationContext()
        {
        }

        public ReservationContext(DbContextOptions<ReservationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Reservation> Reservation { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=MABBAS-LT-10909\\SQLEXPRESS;Initial Catalog=FRONTEND_RESERVATION;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.ToTable("reservation");

                entity.Property(e => e.AptSuite)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("apt_suite");

                entity.Property(e => e.ArrivalTime)
                    .HasColumnType("date")
                    .HasColumnName("arrival_time");

                entity.Property(e => e.BirthDay)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("birth_day");

                entity.Property(e => e.BreakFast).HasColumnName("break_fast");

                entity.Property(e => e.CardCvc)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("card_cvc")
                    .IsFixedLength(true);

                entity.Property(e => e.CardExp)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("card_exp");

                entity.Property(e => e.CardNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("card_number");

                entity.Property(e => e.CardType)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("card_type")
                    .IsFixedLength(true);

                entity.Property(e => e.CheckIn).HasColumnName("check_in");

                entity.Property(e => e.City)
                    .IsRequired()
                    .HasColumnName("city");

                entity.Property(e => e.Cleaning).HasColumnName("cleaning");

                entity.Property(e => e.Dinner).HasColumnName("dinner");

                entity.Property(e => e.EmailAddress)
                    .IsRequired()
                    .HasColumnName("email_address");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("first_name");

                entity.Property(e => e.FoodBill).HasColumnName("food_bill");

                entity.Property(e => e.Gender)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("gender");

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("last_name");

                entity.Property(e => e.LeavingTime)
                    .HasColumnType("date")
                    .HasColumnName("leaving_time");

                entity.Property(e => e.Lunch).HasColumnName("lunch");

                entity.Property(e => e.NumberGuest).HasColumnName("number_guest");

                entity.Property(e => e.PaymentType)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("payment_type")
                    .IsFixedLength(true);

                entity.Property(e => e.PhoneNumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("phone_number");

                entity.Property(e => e.RoomFloor)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("room_floor")
                    .IsFixedLength(true);

                entity.Property(e => e.RoomNumber)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("room_number")
                    .IsFixedLength(true);

                entity.Property(e => e.RoomType)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("room_type")
                    .IsFixedLength(true);

                entity.Property(e => e.SSurprise).HasColumnName("s_surprise");

                entity.Property(e => e.State)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("state");

                entity.Property(e => e.StreetAddress)
                    .IsRequired()
                    .HasColumnName("street_address");

                entity.Property(e => e.SupplyStatus).HasColumnName("supply_status");

                entity.Property(e => e.TotalBill).HasColumnName("total_bill");

                entity.Property(e => e.Towel).HasColumnName("towel");

                entity.Property(e => e.ZipCode)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("zip_code")
                    .IsFixedLength(true);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}